/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {
    public static void main(String[] args) {
        Graph<String> graph1 = new Graph<>();

        graph1.addNode("Amman");
        graph1.addNode("Zarqa");
        graph1.addNode("Irbid");
        graph1.addNode("Salt");

        try {
            graph1.addEdge("Amman","Zarqa",10);
            graph1.addEdge("Amman","Irbid",13);
            System.out.println(graph1.getNeighbors("Amman"));
        }
        catch(NodeNotFoundException ex){
            System.out.println(ex.getMessage());
        }

        System.out.println(graph1);
        System.out.println(graph1.getSize());
        System.out.println(graph1.getNodes());
    }
}
