/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

public class App {


    public static void main(String[] args) {
        System.out.println(fib(-1	));
    }
    public static int fib(int num){
        int n1=0,n2=1,n3=1;
        if (num<=0){
          return num;
        }
        for(int i=2;i<=num;++i)
        {
            n3=n1+n2;
            n1=n2;
            n2=n3;
        }
        return n3;
    }


}
