/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

public class Main {
  public static void main(String[] args) {
    Linkedlist linklist = new Linkedlist();
    // Linkedlist linklist2 = new Linkedlist();
//    linklist2.append("🧑🧒");
//    linklist2.append("👔👗");

   linklist.insert(1);
   linklist.append(5);
   linklist.append(4);
   linklist.append(2);
   linklist.append(8);
    System.out.println(linklist);

    // System.out.println(linklist.palindrome());

//    linklist.append("👔👗");
//
//    linklist.append("👶");


//    System.out.println(linklist.toString());
//
//    System.out.println(linklist.kthFromEnd(0));
    //linklist.insertAfter("khear","pozan");

//    System.out.println(linklist.toString());
//    System.out.println(linklist.zipLists(linklist2));

//    linklist.reverse();
//    System.out.println(linklist);
//    System.out.println(linklist);

//    System.out.println(linklist.includes("deyaa"));
  }
}
