/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

public class App {


    public static void main(String[] args) {
        HashTable<String, Integer> friends = new HashTable<>();
        friends.add("person", 300);
        friends.add("noBody", 400);
        friends.add("dontKnow", 200);
        friends.add("else", 100);

        System.out.println("The size is => " + friends.getSize());
        System.out.println("The dontKnow allowance is => " + friends.get("else"));
        System.out.println(friends.contains("else"));
        System.out.println("The Index  is => " + friends.hash("person"));

    }
}
