/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        InsertionSort sort = new InsertionSort();
        int[] array = {8,4,23,42,16,15};
        System.out.println(Arrays.toString(array));
        System.out.println(Arrays.toString(sort.insertionSort(array)));
    }
}
