/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void createNewTree(){
        BinarySearchTree<Integer> tree = new BinarySearchTree<>();
        assertEquals(true, tree instanceof BinaryTree);
    }
    @Test
    public void CreateEmptyTree(){
        BinaryTree<Integer> tree = new BinaryTree<>();
        assertNotNull(tree);
    }
    @Test
    public void CreateTreeWithSingleNode(){
        BinarySearchTree<Integer> tree = new BinarySearchTree<>();
        tree.add(1);
        String expected="[1]";
        String actual = tree.preOrder(tree.root).toString();
        assertEquals(expected,actual);
    }
    @Test
    public void AddLeftAndRightChildrenToRoot(){
        BinarySearchTree<Integer> tree = new BinarySearchTree<>();
        tree.add(3);
        tree.add(1);
        tree.add(5);
        String expected="[1, 3, 5]";
        String actual = tree.inOrder(tree.root).toString();
        assertEquals(expected,actual);
    }
    @Test
    public void PreOrderTraversal(){
        BinarySearchTree<Integer> tree = new BinarySearchTree<>();
        tree.add(3);
        tree.add(1);
        tree.add(5);
        ArrayList<Integer> expected=tree.preOrder(tree.root);
        assertArrayEquals(Arrays.asList(3,1,5).toArray(), expected.toArray());
    }

    @Test
    public void InOrderTraversal(){
        BinarySearchTree<Integer> tree = new BinarySearchTree<>();
        tree.add(3);
        tree.add(1);
        tree.add(5);
        ArrayList<Integer> expected=tree.inOrder(tree.root);
        assertArrayEquals(Arrays.asList(1,3,5).toArray(), expected.toArray());
    }

    @Test
    public void PostOrderTraversal(){
        BinarySearchTree<Integer> tree = new BinarySearchTree<>();
        tree.add(3);
        tree.add(1);
        tree.add(5);
        ArrayList<Integer> expected=tree.postOrder(tree.root);
        assertArrayEquals(Arrays.asList(1,5,3).toArray(), expected.toArray());
    }
}
