/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;
import org.junit.jupiter.api.Test;

import java.util.LinkedList;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  Linkedlist MyTestLink = new Linkedlist();
  @Test
  void addNewNode() {
    MyTestLink.insert("marah");
    assertEquals("marah", MyTestLink.head.getData());
  }

  @Test
  void search() {
    
    assertFalse(MyTestLink.includes("deyaa"));

  }
@Test
void print(){
    MyTestLink.insert("deyaa");
    MyTestLink.insert("aldeen");
    MyTestLink.insert("pozan");
    assertEquals("HEAD -> deyaa -> aldeen -> pozan -> NULL", MyTestLink.toString());

  }


}