/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QueueAndStack;

public class App {

    public static void main(String[] args) {
//        QueuePseudo<Integer> pQueue = new QueuePseudo<>();
//        pQueue.enqueue(20);
//        pQueue.enqueue(15);
//        pQueue.enqueue(10);
//        System.out.println(pQueue);
//
//        System.out.println(pQueue.dequeue());
//        System.out.println(pQueue);

//
//        Queue<Integer> queue = new Queue<>();
//        queue.enqueue(10);
//        queue.enqueue(9);
//        queue.enqueue(5);
//        queue.enqueue(6);
//        queue.enqueue(3);
//        queue.enqueue(1);
//
//        System.out.println(queue.toString());
//
//        System.out.println(queue.peek());
//        System.out.println(queue.dequeue());
//        System.out.println(queue.peek());
//
//
//        System.out.println(queue.size);
//
//        System.out.println("-----------");
//        Stack<String> stack = new Stack<>();
//
//        stack.push("1");
//        stack.push("2");
//        stack.push("3");
//
//        System.out.println(stack);
//        AnimalShelter animals = new AnimalShelter();
//        Animal animal1 = new Dog("dog1");
//        Animal animal2 = new Dog("dog2");
//        Animal animal3 = new Cat("cat1");
//        Animal animal4 = new Cat("cat2");
//        // Stretch Goal
//        Animal animal5 = new AnotherAnimal("lion");
//        animals.enqueue(animal1);
//        animals.enqueue(animal2);
//        animals.enqueue(animal3);
//        animals.enqueue(animal4);
//        animals.enqueue(animal5);
//
//        System.out.println(animals);
//
//        System.out.println(animals.dequeue("dog"));
//        System.out.println(animals.dequeue("cat"));
//        System.out.println(animals.dequeue("cute animal"));
//
//
//
//        System.out.println(animals);

        String str = "{(})";


            System.out.println(Brackets.ValidateBrackets(str));





    }
}
