/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Sorts;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    Sort sort = new Sort();
    @Test
    public void testInsertionSortWithNormalArray(){
        int[] array = {8,4,23,42,16,15};
        int[] outputArray = sort.insertionSort(array);
        int[] expectedOutput = {4,8,15,16,23,42};
        assertArrayEquals(expectedOutput,outputArray);
    }

    @Test
    public void testInsertionSortWithEmptyArray(){
        int[] array = {};
        int[] outputArray = sort.insertionSort(array);
        int[] expectedOutput = {};
        assertArrayEquals(expectedOutput,outputArray);
    }

}
